import sys
import peppy
#from Bio import SeqIO

configfile: "config/config.yaml"
pepfile: "config/pep.yaml"

SAMPLES = [x.sample_name for x in pep.samples]
SUBSAMPLE_TABLE = pep.subsample_table
#SUBSAMPLE_NAMES = [expand("{s}-{ss}",s=x, ss=SUBSAMPLE_TABLE[SUBSAMPLE_TABLE['sample_name'] == x] for x in SAMPLES]

MAIN_CONFIG = config.get("MAIN_CONFIG",'config/config.yaml')

subworkflow custom_genome:
    workdir:
        "../../gte21-custom-genome/"
    snakefile:
        "../../gte21-custom-genome/workflow/Snakefile"
    #configfile:
    #    MAIN_CONFIG

rule all:
    input:
        expand("results/star/{s}",s=SAMPLES),
        expand("results/arriba-viz/{s}/fusions.pdf",s=SAMPLES),

def get_from_pep(wc, field):
    tmp = SUBSAMPLE_TABLE[SUBSAMPLE_TABLE['sample_name'] == wc.sample]
    tmp2 = tmp[tmp['subsample_name'] == wc.subsample]
    return tmp2.get(field)

include: "rules/alignment.smk"
include: "rules/arriba.smk"
